In [19]:
import csv
import pandas as pd

xls=pd.ExcelFile('rankexcel.xlsx')
df1=pd.read_excel(xls,'Additional Measure Data')
print(df1)

     Unnamed: 0 Unnamed: 1  Unnamed: 2  Life expectancy    Unnamed: 4  \
0          FIPS      State      County  Life Expectancy  95% CI - Low
1         01000    Alabama         NaN        75.548075       75.4649
2         01001    Alabama     Autauga        77.162581     76.392165
3         01003    Alabama     Baldwin        78.213405      77.82357
4         01005    Alabama     Barbour        74.054741     72.874678
...         ...        ...         ...              ...           ...
3189      56037    Wyoming  Sweetwater        77.533795     76.637095
3190      56039    Wyoming       Teton        87.471434     85.685757
3191      56041    Wyoming       Uinta        78.244365     76.746134
3192      56043    Wyoming    Washakie        79.825612     77.792993
3193      56045    Wyoming      Weston        81.965286     80.014187

         Unnamed: 5              Unnamed: 6  \
0     95% CI - High  Life Expectancy (AIAN)
1         75.631251              114.483062
2         77.932998                     NaN
3          78.60324                     NaN
4         75.234805                     NaN
...             ...                     ...
3189      78.430495                     NaN
3190      89.257111                     NaN
3191      79.742595                     NaN
3192      81.858231                     NaN
3193      83.916385                     NaN

                               Unnamed: 7  \
0     Life Expectancy (AIAN) 95% CI - Low
1                              100.157886
2                                     NaN
3                                     NaN
4                                     NaN
...                                   ...
3189                                  NaN
3190                                  NaN
3191                                  NaN
3192                                  NaN
3193                                  NaN

                                Unnamed: 8               Unnamed: 9  ...  \
0     Life Expectancy (AIAN) 95% CI - High  Life Expectancy (Asian)  ...
1                               128.808237                88.144914  ...
2                                      NaN                      NaN  ...
3                                      NaN                83.027953  ...
4                                      NaN                      NaN  ...
...                                    ...                      ...  ...
3189                                   NaN                      NaN  ...
3190                                   NaN                      NaN  ...
3191                                   NaN                      NaN  ...
3192                                   NaN                      NaN  ...
3193                                   NaN                      NaN  ...

     Unnamed: 266  % Non-Hispanic White          Unnamed: 268  \
0      % Hispanic  # Non-Hispanic White  % Non-Hispanic White
1        4.553734               3200828             65.280588
2        2.990925                 41215             73.770785
3        4.718815                185747             83.207307
4        4.524832                 11235             45.511626
...           ...                   ...                   ...
3189    15.993198                 33561             79.259854
3190    15.146608                 19000             80.975111
3191      9.25047                 17657             87.298527
3192    14.196028                  6417             82.216528
3193     4.114335                  6236             90.024542

      % not proficient in English                 Unnamed: 270  Unnamed: 271  \
0     # Not Proficient in English  % Not Proficient in English  95% CI - Low
1                           50445                     1.100683      1.044536
2                             419                     0.803251      0.281955
3                            1425                     0.708458      0.420294
4                             454                     1.890721      1.044348
...                           ...                          ...           ...
3189                          459                     1.133165      0.482233
3190                          876                     3.960396      2.232294
3191                          179                     0.943048      0.158627
3192                           19                     0.251123             0
3193                           10                      0.15024           NaN

       Unnamed: 272  % Females  % Rural Unnamed: 275
0     95% CI - High   % Female  # Rural      % Rural
1           1.15683  51.673922  1957932    40.963183
2          1.324548  51.507992    22921    42.002162
3          0.996622  51.509627    77060    42.279099
4          2.737094  47.079316    18613    67.789635
...             ...        ...      ...          ...
3189       1.784098    48.4968     4782    10.916313
3190       5.688498  48.252642     9887     46.43092
3191        1.72747  49.451201     9101    43.095937
3192       1.310688  49.224856     3068    35.954529
3193            NaN   47.68298     3931    54.536626

[3194 rows x 276 columns]

In [20]:
wa_le=df1.iloc[3001:3041, 0:4]
print(wa_le)

     Unnamed: 0  Unnamed: 1    Unnamed: 2 Life expectancy
3001      53000  Washington           NaN       80.420203
3002      53001  Washington         Adams       80.204006
3003      53003  Washington        Asotin         79.3367
3004      53005  Washington        Benton       80.447904
3005      53007  Washington        Chelan       80.627327
3006      53009  Washington       Clallam       78.793721
3007      53011  Washington         Clark       80.067503
3008      53013  Washington      Columbia       78.615416
3009      53015  Washington       Cowlitz        76.91329
3010      53017  Washington       Douglas       82.728132
3011      53019  Washington         Ferry       77.699193
3012      53021  Washington      Franklin       80.976766
3013      53023  Washington      Garfield       80.190195
3014      53025  Washington         Grant       79.073405
3015      53027  Washington  Grays Harbor       76.783433
3016      53029  Washington        Island       81.236069
3017      53031  Washington     Jefferson       81.123221
3018      53033  Washington          King        82.43847
3019      53035  Washington        Kitsap       80.074865
3020      53037  Washington      Kittitas       81.132456
3021      53039  Washington     Klickitat        81.07349
3022      53041  Washington         Lewis       77.396283
3023      53043  Washington       Lincoln       81.065709
3024      53045  Washington         Mason       79.205912
3025      53047  Washington      Okanogan       77.966231
3026      53049  Washington       Pacific        76.84106
3027      53051  Washington  Pend Oreille       77.670271
3028      53053  Washington        Pierce       78.995852
3029      53055  Washington      San Juan         86.1749
3030      53057  Washington        Skagit       80.218356
3031      53059  Washington      Skamania         83.3629
3032      53061  Washington     Snohomish       80.457132
3033      53063  Washington       Spokane       78.617508
3034      53065  Washington       Stevens       79.781101
3035      53067  Washington      Thurston       80.243003
3036      53069  Washington     Wahkiakum       81.215736
3037      53071  Washington   Walla Walla       80.251265
3038      53073  Washington       Whatcom       81.301902
3039      53075  Washington       Whitman        81.01296
3040      53077  Washington        Yakima       77.920805

In [26]:
life_exp=wa_le.reset_index()
print(life_exp)

    index Unnamed: 0  Unnamed: 1    Unnamed: 2 Life expectancy
0    3001      53000  Washington           NaN       80.420203
1    3002      53001  Washington         Adams       80.204006
2    3003      53003  Washington        Asotin         79.3367
3    3004      53005  Washington        Benton       80.447904
4    3005      53007  Washington        Chelan       80.627327
5    3006      53009  Washington       Clallam       78.793721
6    3007      53011  Washington         Clark       80.067503
7    3008      53013  Washington      Columbia       78.615416
8    3009      53015  Washington       Cowlitz        76.91329
9    3010      53017  Washington       Douglas       82.728132
10   3011      53019  Washington         Ferry       77.699193
11   3012      53021  Washington      Franklin       80.976766
12   3013      53023  Washington      Garfield       80.190195
13   3014      53025  Washington         Grant       79.073405
14   3015      53027  Washington  Grays Harbor       76.783433
15   3016      53029  Washington        Island       81.236069
16   3017      53031  Washington     Jefferson       81.123221
17   3018      53033  Washington          King        82.43847
18   3019      53035  Washington        Kitsap       80.074865
19   3020      53037  Washington      Kittitas       81.132456
20   3021      53039  Washington     Klickitat        81.07349
21   3022      53041  Washington         Lewis       77.396283
22   3023      53043  Washington       Lincoln       81.065709
23   3024      53045  Washington         Mason       79.205912
24   3025      53047  Washington      Okanogan       77.966231
25   3026      53049  Washington       Pacific        76.84106
26   3027      53051  Washington  Pend Oreille       77.670271
27   3028      53053  Washington        Pierce       78.995852
28   3029      53055  Washington      San Juan         86.1749
29   3030      53057  Washington        Skagit       80.218356
30   3031      53059  Washington      Skamania         83.3629
31   3032      53061  Washington     Snohomish       80.457132
32   3033      53063  Washington       Spokane       78.617508
33   3034      53065  Washington       Stevens       79.781101
34   3035      53067  Washington      Thurston       80.243003
35   3036      53069  Washington     Wahkiakum       81.215736
36   3037      53071  Washington   Walla Walla       80.251265
37   3038      53073  Washington       Whatcom       81.301902
38   3039      53075  Washington       Whitman        81.01296
39   3040      53077  Washington        Yakima       77.920805

In [31]:
life_exp2=life_exp.rename(columns={"index":"number"})
print(life_exp2)

    Unnamed: 1    Unnamed: 2 Life expectancy
0   Washington           NaN       80.420203
1   Washington         Adams       80.204006
2   Washington        Asotin         79.3367
3   Washington        Benton       80.447904
4   Washington        Chelan       80.627327
5   Washington       Clallam       78.793721
6   Washington         Clark       80.067503
7   Washington      Columbia       78.615416
8   Washington       Cowlitz        76.91329
9   Washington       Douglas       82.728132
10  Washington         Ferry       77.699193
11  Washington      Franklin       80.976766
12  Washington      Garfield       80.190195
13  Washington         Grant       79.073405
14  Washington  Grays Harbor       76.783433
15  Washington        Island       81.236069
16  Washington     Jefferson       81.123221
17  Washington          King        82.43847
18  Washington        Kitsap       80.074865
19  Washington      Kittitas       81.132456
20  Washington     Klickitat        81.07349
21  Washington         Lewis       77.396283
22  Washington       Lincoln       81.065709
23  Washington         Mason       79.205912
24  Washington      Okanogan       77.966231
25  Washington       Pacific        76.84106
26  Washington  Pend Oreille       77.670271
27  Washington        Pierce       78.995852
28  Washington      San Juan         86.1749
29  Washington        Skagit       80.218356
30  Washington      Skamania         83.3629
31  Washington     Snohomish       80.457132
32  Washington       Spokane       78.617508
33  Washington       Stevens       79.781101
34  Washington      Thurston       80.243003
35  Washington     Wahkiakum       81.215736
36  Washington   Walla Walla       80.251265
37  Washington       Whatcom       81.301902
38  Washington       Whitman        81.01296
39  Washington        Yakima       77.920805